// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADCJdw4wozLhFmMEimMin8KhPOLUcbxc4',
    appId: '1:519656081527:web:a08ebbda09fa20f6a95e72',
    messagingSenderId: '519656081527',
    projectId: 'expense-tracker-c2f86',
    authDomain: 'expense-tracker-c2f86.firebaseapp.com',
    storageBucket: 'expense-tracker-c2f86.firebasestorage.app',
    measurementId: 'G-MERH5P4S6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1KchjDczNpfqKgC6RC9byxwCSU9UFGJU',
    appId: '1:519656081527:android:58fdda4f074913cba95e72',
    messagingSenderId: '519656081527',
    projectId: 'expense-tracker-c2f86',
    storageBucket: 'expense-tracker-c2f86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKq2PTpEvJQwky45DkCuo52Y0TflfO63A',
    appId: '1:519656081527:ios:8a5dc44e4a65ff3ca95e72',
    messagingSenderId: '519656081527',
    projectId: 'expense-tracker-c2f86',
    storageBucket: 'expense-tracker-c2f86.firebasestorage.app',
    iosBundleId: 'com.example.expensetracker',
  );
}
